visualn_dataset.visualn_data_set_type.*:
  type: config_entity
  label: 'VisualN Data Set type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    resource_provider_field:
      type: string
      label: 'Resource provider field'
