<?php

/**
 * @file
 * Contains visualn_embed_token.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_embed_token_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_embed_token module.
    case 'help.page.visualn_embed_token':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embed VisualN Drawings into site content via tokens') . '</p>';
      return $output;

    default:
  }
}
