<?php

/**
 * @file
 * Contains visualn_file.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_file_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_file module.
    case 'help.page.visualn_file':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables VisualN support for files') . '</p>';
      return $output;

    default:
  }
}
