<?php

/**
 * @file
 * Contains visualn_file.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_file_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_file module.
    case 'help.page.visualn_file':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables VisualN support for files') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function visualn_file_theme($existing, $type, $theme, $path) {
  return [
    'visualn_image_formatter' => [
      'variables' => [
        'image_items' => NULL,
        'visualn_drawing_build' => NULL,
        'label' => NULL,
        'element' => NULL
      ],
    ],
  ];
}

function template_preprocess_visualn_image_formatter(&$variables, $hook) {
  // @todo: Get label and other variables for the template, see template_preprocess_field() for example.
}
