<?php

/**
 * @file
 * Contains visualn_styles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_styles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_styles module.
    case 'help.page.visualn_styles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('VisualN ready to use styles') . '</p>';
      return $output;

    default:
  }
}
