visualn.visualn_drawer.*:
  type: config_entity
  label: 'VisualN Drawer config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    base_drawer_id:
      type: string
      label: 'Base Drawer ID'
    drawer_config:
      type: serial
    modifiers:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          # @todo: see image.effect schema
          #data:
            #type: drawer.modifier.[%parent.id]
          weight:
            type: integer
          uuid:
            type: string
