# @todo: Fill-in the file. See image.schema.yml for reference

visualn.visualn_style.*:
  type: config_entity
  label: 'VisualN style config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    drawer_id:
      type: string
      label: 'Drawer ID'
    drawer_type:
      type: string
      label: 'Drawer type'
    # @todo: this property is added for consistency, later may replace drawer_type
    #   one of the should be deleted
    drawer_type_prefix:
      type: string
      label: 'Drawer type prefix'
    drawer_config:
      type: serial
      label: 'Drawer config'
