visualn.visualn_setup.*:
  type: config_entity
  label: 'VisualN Setup config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    baker_id:
      type: string
      label: 'Baker ID'
    baker_config:
      type: serial
      label: 'Baker config'
