<?php

/**
 * @file
 * Contains visualn_resource.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_resource_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_resource module.
    case 'help.page.visualn_resource':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('VisualN support for url resources') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_visualn_resource_format_info_alter().
 */
function visualn_resource_visualn_resource_format_info_alter(&$definitions) {
  // @todo: disable visualn_xml (at least temporarily until fixed)
  $ids = ['visualn_json', 'visualn_csv', 'visualn_tsv', 'visualn_xml'];
  // @todo: maybe add directly to plugins annotation
  foreach ($definitions as $k => $definition) {
    if (in_array($definition['id'], $ids)) {
      $definitions[$k]['groups'][] = 'visualn_resource_widget';
    }
  }
}
