visualn_drawing.visualn_drawing_type.*:
  type: config_entity
  label: 'VisualN Drawing type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    thumbnail_path:
      type: string
      label: 'Thumbnail path'
    uuid:
      type: string
    drawing_fetcher_field:
      type: string
      label: 'Drawing fetcher field'
