<?php

/**
 * @file
 * Contains visualn_iframe.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_iframe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_iframe module.
    case 'help.page.visualn_iframe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enable visualizations share via iframe embed code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function visualn_iframe_theme() {
  return [
    'visualn_iframe' => [
      'render element' => 'children',
    ],
  ];
}

function visualn_iframe_theme_suggestions_page(array $variables) {
  // @todo: check by route name
  $path = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  if (isset($path[0]) && $path[0] == 'visualn-iframe') {
    return 'visualn_iframe';
  }
}

// https://drupal.stackexchange.com/questions/137279/how-to-disable-toolbar-on-certain-pages-theme
function visualn_iframe_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_top') {
    $group = $implementations['visualn_iframe'];
    unset($implementations['visualn_iframe']);
    unset($implementations['toolbar']);
    $implementations['visualn_iframe'] = $group;
  }
}

function visualn_iframe_page_top(array &$page_top) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $path = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  // @todo: check by route name
  if (!(isset($path[0]) && $path[0] == 'visualn-iframe')) {
  //if ($theme != "theme where you don't want the toolbar" && \Drupal::moduleHandler()->moduleExists('toolbar')) {
    toolbar_page_top($page_top);
  }
}
