<?php

/**
 * @file
 * Contains visualn_data_sources.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\visualn_data_sources\Entity\VisualNDataSource;

/**
 * Implements hook_help().
 */
function visualn_data_sources_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_data_sources module.
    case 'help.page.visualn_data_sources':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables Data Sources functionality for creating VisualN drawings.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function visualn_data_sources_theme() {
  $theme = [];
  $theme['visualn_data_set'] = [
    'render element' => 'elements',
    'file' => 'visualn_data_set.page.inc',
    'template' => 'visualn_data_set',
  ];
  $theme['visualn_data_set_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'visualn_data_set.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function visualn_data_sources_theme_suggestions_visualn_data_set(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#visualn_data_set'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'visualn_data_set__' . $sanitized_view_mode;
  $suggestions[] = 'visualn_data_set__' . $entity->bundle();
  $suggestions[] = 'visualn_data_set__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'visualn_data_set__' . $entity->id();
  $suggestions[] = 'visualn_data_set__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}


function visualn_data_source_options($include_empty = TRUE) {
  $data_sources = VisualNDataSource::loadMultiple();
  $options = array();
  if ($include_empty && !empty($data_sources)) {
    $options[''] = t('- None -');
  }
  foreach ($data_sources as $name => $data_source) {
    $options[$name] = $data_source->label();
  }

  if (empty($options)) {
    $options[''] = t('No defined data sources');
  }
  return $options;
}
